web3j:
  client-address: https://ropsten.infura.io/A6YAM6J99HuuW8LafBEv
  admin-client: false
  httpTimeoutSeconds: 600
#spring.resources.static-locations=classpath:/resources/
spring:
  mvc:
    async:
      request-timeout: -1